apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: hello-world # Should match .spec.template.metadata.labels (which pods the replicaSet applies to)
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-kubernetes
        image: mcmah309/hello-world-kubernetes:latest
        ports:
        - containerPort: 8000
---
# Exposes the deployment
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world # The selector should match the label in the deployment
  ports:
    - name: http # optional, used if need to expose more than one
      protocol: TCP # optional, defaults to TCP if not specified
      port: 80  # The port exposed by the LoadBalancer
      targetPort: 8000  # The port your application is listening on
  type: LoadBalancer